#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "blaslapack.h"
#include "def.h"
#include "evsl.h"
#include "internal_proto.h"
#include "struct.h"

double rec(const double a) { return 1.0 / a; }  // Reciprocal

double isqrt(const double a) { return 1.0 / sqrt(a); }  // Inverse square root

/**----------------------------------------------------------------------
 *
 *    Evalutes ffun at the xi's.
 *    Assumes a transformation of original inetrval [a b] into [-1, 1] so:
 *    the xi's are between -1 and 1
 *
 *    @param[in] c Value to increase xi's by
 *    @param[in] h Value to scale xi's by
 *    @param[in] *xi Points for which to evaluate ffun at
 *    @param[in] npts Number of points in xi to evaluate
 *    @param[in] ffun Function to evaluate
 *
 *    @param[out] yi ffun evaluated at xi's
 *
 *
 *----------------------------------------------------------------------*/

int apfun(const double c, const double h, const double *const xi,
          double (*ffun)(double), const int npts, double *yi) {
  int i = 0;
  for (i = 0; i < npts; i++) {
    yi[i] = ffun(c + h * xi[i]);
  }
  return 0;
}

/**
 * Computes y=P(A) v, where pn is a Cheb. polynomial expansion
 *
 * This explicitly calls matvec, so it can be useful for implementing
 * user-specific matrix-vector multiplication.
 *
 * @param pol Struct containing the paramenters and expansion coefficient of
 * the polynomail.
 * @param v input vector
 *
 * @param[out] y p(A)v
 *
 * @b Workspace
 * @param w Work vector of length 3*n [allocate before call]
 * @param v is untouched
 **/
int pnav(double *mu, const int m, const double cc, const double dd, double *v,
         double *y, double *w) {  // Really just ChebAv
  int n = evsldata.n;
  /*-------------------- pointers to v_[k-1],v_[k], v_[k+1] from w */
  double *vk = w;
  double *vkp1 = w + n;
  double *vkm1 = vkp1 + n;
  /*-------------------- */
  int k, i;
  double t, s, *tmp, t1 = 1.0 / dd, t2 = 2.0 / dd;
  /*-------------------- vk <- v; vkm1 <- zeros(n,1) */
  memcpy(vk, v, n * sizeof(double));
  memset(vkm1, 0, n * sizeof(double));
  /*-------------------- special case: k == 0 */
  s = mu[0];
  for (i = 0; i < n; i++) {
    y[i] = s * vk[i];
  }
  /*-------------------- degree loop. k IS the degree */
  for (k = 1; k <= m; k++) {
    /*-------------------- y = mu[k]*Vk + y */
    t = k == 1 ? t1 : t2;
    /*-------------------- */
    s = mu[k];
    matvec_B(vk, vkp1);

    for (i = 0; i < n; i++) {
      vkp1[i] = t * (vkp1[i] - cc * vk[i]) - vkm1[i];
      /*-------------------- for degree 2 and up: */
      y[i] += s * vkp1[i];
    }
    /*-------------------- next: rotate vectors via pointer exchange */
    tmp = vkm1;
    vkm1 = vk;
    vk = vkp1;
    vkp1 = tmp;
  }

  return 0;
}

/**----------------------------------------------------------------------
 *
 *    Finds the least-square polynomial approximation to function ffun
 *    in interval given by intv
 *
 *    @param[in] *intv Stores the interval of interest \\
 *        intv[0:1] Interval of interest
 *    @param[in] maxDeg Maximum degree of the polynomial appoximation
 *    @param[in] ffun Function to generate an approximation for
 *    @param[in] tol Tolerance for approximation
 *
 *    @param[out] pol polparams struct \\
 *      Contains: cc = (a + b) / 2 \\
 *                dd = (b - a) / 2 \\
 *                mu = coefficients \\
 *                deg = number of coefficients
 *
 *
 *----------------------------------------------------------------------*/

int lsPol(const double *const intv, const int maxDeg, double (*ffun)(double),
          const double tol, polparams *pol) {
  const double a = intv[0];
  const double b = intv[1];
  pol->cc = (a + b) / 2;
  pol->dd = (b - a) / 2;
  //------------------------- Number of points for Gauss-Chebyshev
  // integration
  const int npts = maxDeg * 4;

  double *theti;
  Malloc(theti, npts, double);
  int i = 0;
  for (i = 0; i < npts * 2; i += 2) {
    theti[i / 2] = (i + 1) * (PI / (2 * npts));
  }

  double *xi;
  Malloc(xi, npts, double);

  for (i = 0; i < npts; i++) {
    xi[i] = cos(theti[i]);
  }

  double *gi;
  Malloc(gi, npts, double);
  apfun(pol->cc, pol->dd, xi, ffun, npts, gi);
  free(xi);

  // ----------------------- Degree loop
  // ----------------------- Each coefficient generated by gauss-Chebyshev
  // quadature.
  const int ptsNrm = 300;  // Number of points for norm infinity
  Malloc(xi, ptsNrm, double);
  linspace(-1, 1, ptsNrm, xi);

  // Compute f(x) once

  double *yx;
  Malloc(yx, npts, double);
  apfun(pol->cc, pol->dd, xi, ffun, ptsNrm, yx);

  double *yi;
  Malloc(yi, npts, double);

  double *ya;
  Malloc(ya, npts, double);

  double na;

  int k = 0;
  for (k = 0; k < maxDeg; k++) {
    for (i = 0; i < npts; i++) {
      yi[i] = cos(k * theti[i]);
    }
    double t = 2.0 / npts;
    if (k == 0) {
      t = t * 0.5;
    }
    double sum = 0;
    for (i = 0; i < npts; i++) {
      sum += yi[i] * gi[i];
    }
    pol->mu[k] = t * sum;
    chebxPltd(k, pol->mu, ptsNrm, xi, ya);
    double nrm = 0;
    for (i = 0; i < ptsNrm; i++) {
      na = (ya[i] - yx[i]) / yx[i];
      nrm += fabs(na);
    }
    if (nrm < tol) {
      pol->deg = k + 1;
      break;
    }
  }
  free(xi);
  free(yi);
  free(ya);
  free(yx);
  free(theti);
  free(gi);
  return 0;
}
