#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include "blaslapack.h"
#include "def.h"
#include "evsl.h"
#include "float.h"
#include "internal_proto.h"
#include "string.h"  //for memset
#include "struct.h"

/**----------------------------------------------------------------------
 *
 *    Finds the least-square polynomial approximation to function ffun
 *    in interval given by intv
 *
 *    @param[in] *intv Stores the interval of interest \\
 *        intv[0:1] Interval of interest
 *    @param[in] maxDeg Maximum degree of the polynomial appoximation
 *    @param[in] ffun Function to generate an approximation for
 *    @param[in] tol Tolerance for approximation
 *
 *    @param[out] pol polparams struct \\
 *      Contains: cc = (a + b) / 2 \\
 *                dd = (b - a) / 2 \\
 *                mu = coefficients \\
 *                deg = number of coefficients
 *
 *    @warning The polparams struct returned only contains the following members: mu, cc, dd, deg (This is all that is used by ChebAv used by landosG2).
 *
 *
 *----------------------------------------------------------------------*/

int lsPol(const double* const intv, const int maxDeg, double (*ffun)(double),
           const double tol, polparams* pol) {
  const double a = intv[0];
  const double b = intv[1];
  pol->cc = (a + b) / 2;
  pol->dd = (b - a) / 2;
  //------------------------- Number of points for Gauss-Chebyshev
  // integration
  const int npts = maxDeg * 4;

  double* theti;
  Malloc(theti, npts, double);
  int i = 0;
  for (i = 0; i < npts * 2; i += 2) {
    theti[i / 2] = (i + 1) * (PI / (2 * npts));
  }

  double* xi;
  Malloc(xi, npts, double);

  for (i = 0; i < npts; i++) {
    xi[i] = cos(theti[i]);
  }

  double* gi;
  Malloc(gi, npts, double);
  apfun(pol->cc, pol->dd, xi, ffun, npts, gi);
  free(xi);

  // ----------------------- Degree loop
  // ----------------------- Each coefficient generated by gauss-Chebyshev
  // quadature.
  const int ptsNrm = 300;  // Number of points for norm infinity
  Malloc(xi, ptsNrm, double);
  linspace(-1, 1, ptsNrm, xi);

  // Compute f(x) once

  double* yx;
  Malloc(yx, npts, double);
  apfun(pol->cc, pol->dd, xi, ffun, ptsNrm, yx);

  double* yi;
  Malloc(yi, npts, double);

  double* ya;
  Malloc(ya, npts, double);

  double na;

  int k = 0;
  for (k = 0; k < maxDeg; k++) {
    for (i = 0; i < npts; i++) {
      yi[i] = cos(k * theti[i]);
    }
    double t = 2.0 / npts;
    if (k == 0) {
      t = t * 0.5;
    }
    double sum = 0;
    for (i = 0; i < npts; i++) {
      sum += yi[i] * gi[i];
    }
    pol->mu[k] = t * sum;
    chebxPltd(k, pol->mu, ptsNrm, xi, ya);
    double nrm = 0;
    for (i = 0; i < ptsNrm; i++) {
      na = (ya[i] - yx[i]) / yx[i];
      nrm += fabs(na);
    }
    if (nrm < tol) {
      pol->deg = k + 1;
      break;
    }
  }
  free(xi);
  free(yi);
  free(ya);
  free(yx);
  free(theti);
  free(gi);
  return 0;
}
